lab50:
  window:   
    - editor
    - readme
    - terminal

  files:
    - !exclude "*"
    - !include "salesTax.cpp"
    - !include "salesTax.java"

check50: 
  files: &check50_files
    - !require "salesTax.cpp"
    - !require "salesTax.java"

submit50: 
  files: *check50_files
  style: true